FROM debian

ADD debian.list /etc/apt/sources.list.d/


RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p veraida.com/img && \
    chmod -R 754 /var/www/veraida.com/ && \
    useradd Verusik  && groupadd pogibeleva && usermod -a -G pogibeleva Verusik  && \
    chown -R Verusik :pogibeleva /var/www/veraida.com && \
    sed -i 's$/var/www/html$/var/www/veraida.com$g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Verusik /g' /etc/nginx/nginx.conf
	
ADD index.html /var/www/veraida.com/
ADD img.jpg /var/www/veraida.com/img/
CMD ["nginx", "-g", "daemon off;"]